### PR TITLE
Add ability to filter routes to a certain prefix

### PR DESCRIPTION
**Pull request by overint**
I have a bunch of non-api routes in my app, which I don't need docs generated for. This PR adds a `--filter` option which you can use to filter the generation to a certain prefix.

Let me know if there are any issues or changes you would like.

### CODE REVIEW

**Comment by mtrajano** [comment]
@overint Hey thanks for the contribution! I had something similar on my TODO. Would you mind just writing a couple of tests to compliment your changes? In any case it looks good to me.

I did merge your other pr though.

**Comment by overint** [comment]
No worries, will get some tests written up and update the PR.

Thanks!

**Comment by overint** [comment]
I've added tests, let me know if anything else is needed, thanks!

**Comment by overint** [comment]
Thanks for merging. If you need any help with other feature let me know 👍

**Pull request merged**
